<%@ Page Title="" Language="C#" MasterPageFile="~/TeacherDashboard/main.Master" AutoEventWireup="true" CodeBehind="assignment.aspx.cs" Inherits="LMS.TeacherDashboard.WebForm3" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"></asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="row mb-0">
        <div class="col">
            <div class="form-floating mb-3">
                <asp:DropDownList CssClass="form-control" ID="ddDepart" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddDepart_SelectedIndexChanged">
                    <asp:ListItem>Select Department</asp:ListItem>
                </asp:DropDownList>
                <label for="ddDepart">Department</label>
            </div>
        </div>
        <div class="col">
            <div class="form-floating mb-3">
                <asp:DropDownList CssClass="form-control" ID="ddClass" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddClass_SelectedIndexChanged">
                    <asp:ListItem>Select Class</asp:ListItem>
                </asp:DropDownList>
                <label for="ddClass">Class</label>
            </div>
        </div>
        <div class="col">
            <div class="form-floating mb-3">
                <asp:DropDownList CssClass="form-control" ID="ddSem" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddSem_SelectedIndexChanged">
                    <asp:ListItem>Select Semister</asp:ListItem>
                </asp:DropDownList>
                <label for="ddSem">Semester</label>
            </div>
        </div>
        <div class="col">
            <div class="form-floating mb-3">
                <asp:DropDownList CssClass="form-control" ID="ddDiv" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddDiv_SelectedIndexChanged">
                    <asp:ListItem>Select Division</asp:ListItem>
                </asp:DropDownList>
                <label for="ddDiv">Division</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-2">
            <div class="form-floating mb-3">
                <asp:DropDownList CssClass="form-control" ID="ddSearchBy" runat="server" AutoPostBack="true">
                    <asp:ListItem>First name</asp:ListItem>
                    <asp:ListItem>Middle name</asp:ListItem>
                    <asp:ListItem>Last name</asp:ListItem>
                </asp:DropDownList>
                <label for="ddDiv">Search by</label>
            </div>
        </div>
        <div class="col m-0">
            <div class="form-floating mb-3">
                <asp:TextBox CssClass="form-control" ID="txtSearch" runat="server" placeholder="Search"></asp:TextBox>
                <label for="txtSearch">Search</label>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card p-0">
            <div class="card-header text-light d-flex justify-content-between align-items-center bg-success fw-bold">
                Student List
				
                <asp:Button ID="Button2" class="btn btn-outline-light" runat="server" Text="Add New" OnClick="Button2_Click"></asp:Button>
            </div>
            <div class="card-body m-0 p-0">
                <asp:GridView ID="gridview" CssClass="table table-striped table-bordered table-sm"  runat="server" AutoGenerateColumns="False" DataKeyNames="assignemtId"  AllowPaging="True" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="Select from drop down" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
                            <Columns>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="assignemtId" HeaderText="assignemtId" InsertVisible="False" ReadOnly="True" SortExpression="assignemtId">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="title" HeaderText="title" SortExpression="title">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="detail" HeaderText="detail" SortExpression="detail">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="files" HeaderText="files" SortExpression="files">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="submitionDate" HeaderText="submitionDate" SortExpression="submitionDate">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="givenOn" HeaderText="givenOn" SortExpression="givenOn">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="byStaff" HeaderText="byStaff" SortExpression="byStaff">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="divName" HeaderText="divName" SortExpression="divName">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="className" HeaderText="className" SortExpression="className">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="semName" HeaderText="semName" SortExpression="semName">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="departName" HeaderText="departName" SortExpression="departName">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="editDate" HeaderText="editDate" SortExpression="editDate">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                    </Columns>
                </asp:GridView>
            </div>
        </div>
    </div>
</asp:Content>
