<%@ Page Title="" Language="C#" MasterPageFile="~/TeacherDashboard/main.Master" AutoEventWireup="true" CodeBehind="attendence.aspx.cs" Inherits="LMS.TeacherDashboard.WebForm9" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="row mb-0">
        <div class="col">
            <div class="form-floating mb-3">
                <asp:DropDownList CssClass="form-control" ID="ddDepart" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddDepart_SelectedIndexChanged">
                    <asp:ListItem>Select Department</asp:ListItem>
                </asp:DropDownList>
                <label for="ddDepart">Department</label>
            </div>
        </div>
        <div class="col">
            <div class="form-floating mb-3">
                <asp:DropDownList CssClass="form-control" ID="ddClass" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddClass_SelectedIndexChanged">
                    <asp:ListItem>Select Class</asp:ListItem>
                </asp:DropDownList>
                <label for="ddClass">Class</label>
            </div>
        </div>
        <div class="col">
            <div class="form-floating mb-3">
                <asp:DropDownList CssClass="form-control" ID="ddSem" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddSem_SelectedIndexChanged">
                    <asp:ListItem>Select Semister</asp:ListItem>
                </asp:DropDownList>
                <label for="ddSem">Semester</label>
            </div>
        </div>
        <div class="col">
            <div class="form-floating mb-3">
                <asp:DropDownList CssClass="form-control" ID="ddDiv" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddDiv_SelectedIndexChanged">
                    <asp:ListItem>Select Division</asp:ListItem>
                </asp:DropDownList>
                <label for="ddDiv">Division</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <div class="form-floating mb-3">
                <input type="date" class="form-control" id="dateInput" runat="server" placeholder="Date" />
                <label for="txtSearch">Date</label>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-floating mb-3">
                <asp:DropDownList CssClass="form-control" ID="ddSearchBy" runat="server" AutoPostBack="true">
                    <asp:ListItem>First name</asp:ListItem>
                    <asp:ListItem>Middle name</asp:ListItem>
                    <asp:ListItem>Last name</asp:ListItem>
                </asp:DropDownList>
                <label for="ddDiv">Search by</label>
            </div>
        </div>
        <div class="col m-0">
            <div class="form-floating mb-3">
                <asp:TextBox CssClass="form-control" ID="txtSearch" runat="server" placeholder="Search"></asp:TextBox>
                <label for="txtSearch">Search</label>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card p-0">
            <div class="card-header text-light d-flex justify-content-between align-items-center bg-success fw-bold">
                Attendence List
				
                    <asp:Button ID="Button2" class="btn btn-outline-light" runat="server" Text="Add New" OnClick="Button2_Click"></asp:Button>
            </div>
            <asp:Label ID="msg" runat="server"></asp:Label>
            <div class="card-body m-0 p-0">
                <asp:GridView ID="gridview" CssClass="table table-striped table-bordered table-sm" runat="server" AutoGenerateColumns="False" DataKeyNames="attandenceId" AllowPaging="True" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="Select from drop down" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True">
                    <Columns>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="attandenceId" HeaderText="attandenceId" InsertVisible="False" ReadOnly="True" SortExpression="attandenceId">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="grNo" HeaderText="grNo" SortExpression="grNo">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="fName" HeaderText="fName" SortExpression="fName">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="mName" HeaderText="mName" SortExpression="mName">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="lName" HeaderText="lName" SortExpression="lName">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="divName" HeaderText="divName" SortExpression="divName">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="className" HeaderText="className" SortExpression="className">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="semName" HeaderText="semName" SortExpression="semName">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="departName" HeaderText="departName" SortExpression="departName">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:TemplateField HeaderText="status" SortExpression="status">
                            <EditItemTemplate>
                                <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack = "true" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" SelectedValue='<%# Eval("status") %>'>
                                    <asp:ListItem>Present</asp:ListItem>
                                    <asp:ListItem>Adsent</asp:ListItem>
                                    <asp:ListItem>Leave</asp:ListItem>
                                </asp:DropDownList>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("status") %>'></asp:Label>
                            </ItemTemplate>
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light" />
                            <ItemStyle CssClass="text-center" />
                        </asp:TemplateField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="date" HeaderText="date" SortExpression="date">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="staffName" HeaderText="staffName" SortExpression="staffName">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                        <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-success text-capitalize text-light" DataField="editDate" HeaderText="editDate" SortExpression="editDate">
                            <HeaderStyle CssClass="text-center bg-success text-capitalize text-light"></HeaderStyle>

                            <ItemStyle CssClass="text-center"></ItemStyle>
                        </asp:BoundField>
                    </Columns>

                </asp:GridView>
            </div>
        </div>
    </div>
</asp:Content>
