<%@ Page Title="" Language="C#" MasterPageFile="~/AdminDashboard/main.Master" AutoEventWireup="true" CodeBehind="addDept.aspx.cs" Inherits="LMS.AdminDashboard.WebForm8" %>
	<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"> </asp:Content>
	<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
		<div class="card text-center">
			<div class="card-header text-light bg-danger fw-bold p-2">Add Department</div>
			<div class="card-body">
				<div class="row">
					<div class="col gap-1">
						<asp:label CssClass="text-center" id="libmsg" runat="server" Text="result" Visible="false"></asp:label>
						<div class="form-floating mb-3">
							<asp:TextBox CssClass="form-control" ID="Cdisc" runat="server" placeholder="Department Name"></asp:TextBox>
							<asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="*" ControlToValidate="Cdisc"></asp:RequiredFieldValidator>
							<label for="Cdisc">Department Name</label>
						</div>
						<div class="row form-group ms-5 me-5 gap-1">
							<asp:Button CssClass="btn btn-success w-20 btn-block btn-lg" ID="DepartSubmit" runat="server" Text="Save" OnClick="DepartSubmit_Click" /> </div>
					</div>
				</div>
			</div>
		</div>
		<asp:GridView ID="Gird" runat="server" AutoGenerateColumns="False" CellPadding="4" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" Width="1002px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
			<AlternatingRowStyle BackColor="White" />
			<Columns>
				<asp:BoundField DataField="Did" HeaderText="Did" InsertVisible="False" ReadOnly="True" SortExpression="Did" />
				<asp:BoundField DataField="Dname" HeaderText="Dname" SortExpression="Dname" />
				<asp:BoundField DataField="CreatedDate" HeaderText="CreatedDate" SortExpression="CreatedDate" /> </Columns>
			<EditRowStyle BackColor="#7C6F57" />
			<FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
			<HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
			<PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
			<RowStyle BackColor="#E3EAEB" />
			<SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
			<SortedAscendingCellStyle BackColor="#F8FAFA" />
			<SortedAscendingHeaderStyle BackColor="#246B61" />
			<SortedDescendingCellStyle BackColor="#D4DFE1" />
			<SortedDescendingHeaderStyle BackColor="#15524A" /> </asp:GridView>
		<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:LSMConnectionString %>" SelectCommand="SELECT * FROM [Tbl_Depart]" UpdateCommand="UPDATE [Tbl_Depart] SET [Dname]=@Dname, [CreatedDate]=@CreatedDate WHERE [Did]=@Did" DeleteCommand="DELETE [Tbl_Depart] WHERE [Did]=@Did"></asp:SqlDataSource>
	</asp:Content>