<%@ Page Title="" Language="C#" MasterPageFile="~/AdminDashboard/main.Master" AutoEventWireup="true" CodeBehind="addDept.aspx.cs" Inherits="LMS.AdminDashboard.WebForm8" %>
	<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"> </asp:Content>
	<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
		<div class="row">
			<div class="col-lg-3">
            <div class="card text-center">
			<div class="card-header text-light bg-danger fw-bold p-2">Add Department</div>
			<div class="card-body">
				<div class="row">
					<div class="col gap-1">
						<asp:label CssClass="text-center" id="libmsg" runat="server" Text="result" Visible="false"></asp:label>
						<div class="form-floating mb-3">
							<asp:TextBox CssClass="form-control" ID="Cdisc" runat="server" placeholder="Department Name"></asp:TextBox>
							<!--<asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="*" ControlToValidate="Cdisc"></asp:RequiredFieldValidator>-->
							<label for="Cdisc">Department Name</label>
						</div>
						<div class="row form-group ms-5 me-5 gap-1">
							<asp:Button CssClass="btn btn-success w-20 btn-block btn-lg" ID="DepartSubmit" runat="server" Text="Save" OnClick="DepartSubmit_Click" /> </div>
					</div>
				</div>
			</div>
		</div>
			</div>
		<div class="col-lg-9">
			<div class="card">
				<div class="card-body table-responsive" style="overflow: scroll;">
					<asp:GridView ID="gridview" CssClass="table table-striped table-bordered table-sm" runat="server" AutoGenerateColumns="False" DataKeyNames="departmentId" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Width="800px">
                <Columns>
                    <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="departmentName" HeaderText="departmentName" SortExpression="departmentName" />
                    <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="editDate" HeaderText="editDate" SortExpression="editDate"  />
                </Columns>
            </asp:GridView>
		    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:LSMConnectionString1 %>" SelectCommand="SELECT * FROM [Tbl_Department]" UpdateCommand="UPDATE Tbl_Department SET departmentName=@departmentName, editDate=@editDate where departmentId=@departmentId" DeleteCommand="delete from Tbl_Department where departmentId=@departmentId"></asp:SqlDataSource>
				</div>
			</div>
		</div>
		</div>
	</asp:Content>