<%@ Page Title="" Language="C#" MasterPageFile="~/AdminDashboard/main.Master" AutoEventWireup="true" CodeBehind="addDiv.aspx.cs" Inherits="LMS.AdminDashboard.WebForm2" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="row">
			<div class="col-lg-3">
            <div class="card text-center">
			<div class="card-header text-light bg-danger fw-bold p-2">Add Department</div>
			<div class="card-body">
				<div class="row">
					<div class="col gap-1">
						<asp:label CssClass="text-center" id="libmsg" runat="server" Text="result" Visible="false"></asp:label>
						<div class="form-floating mb-3">
							<asp:DropDownList CssClass="form-control" ID="ddDepart" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddDepart_SelectedIndexChanged">
								<asp:ListItem>Select Department</asp:ListItem>
							</asp:DropDownList>
							<label for="ddDepart">Department</label>
						</div>
						<div class="form-floating mb-3">
							<asp:DropDownList CssClass="form-control" ID="ddClass" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddClass_SelectedIndexChanged">
								<asp:ListItem>Select Class</asp:ListItem>
							</asp:DropDownList>
							<label for="ddClass">Class</label>
						</div>
						<div class="form-floating mb-3">
							<asp:DropDownList CssClass="form-control" ID="ddSem" runat="server" AutoPostBack="true">
								<asp:ListItem>Select Semester</asp:ListItem>
							</asp:DropDownList>
							<label for="ddClass">Semester</label>
						</div>
						<div class="form-floating mb-3">
							<asp:TextBox CssClass="form-control" ID="CDiv" runat="server" placeholder="Division Name"></asp:TextBox>
							<!--<asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="*" ControlToValidate="CDiv"></asp:RequiredFieldValidator>-->
							<label for="CDiv">Division Name</label>
						</div>
						<div class="form-floating mb-3">
							<asp:TextBox CssClass="form-control" ID="CDivSeats" runat="server" placeholder="Division Seats"></asp:TextBox>
							<!--<asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="*" ControlToValidate="CDivSeats"></asp:RequiredFieldValidator>-->
							<label for="CDivSeats">Division Seats</label>
						</div>
						<div class="row form-group ms-5 me-5 gap-1">
							<asp:Button CssClass="btn btn-success w-20 btn-block btn-lg" ID="DivSubmit" runat="server" Text="Save" OnClick="DivSubmit_Click" /> </div>
					</div>
				</div>
			</div>
				</div>
				</div>
		<div class="col-lg-9">
			<div class="card">
				<div class="card-body table-responsive" style="overflow: scroll;">
					<asp:GridView ID="gridview" CssClass="table table-striped table-bordered table-sm" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="divId" DataSourceID="SqlDataSource1">
                        <Columns>
                            <asp:BoundField DataField="divId" HeaderText="divId" InsertVisible="False" ReadOnly="True" SortExpression="divId" />
                            <asp:BoundField DataField="divName" HeaderText="divName" SortExpression="divName" />
                            <asp:BoundField DataField="semName" HeaderText="semName" SortExpression="semName" />
                            <asp:BoundField DataField="seats" HeaderText="seats" SortExpression="seats" />
                            <asp:BoundField DataField="editDate" HeaderText="editDate" SortExpression="editDate" />
                        </Columns>
            </asp:GridView>
		            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:LSMConnectionString1 %>" SelectCommand="SELECT * FROM [Tbl_Div]" UpdateCommand="UPDATE divName=@divName, semName=@semName, seats=@seats, editDate=@editDate  WHERE divId=@divId" DeleteCommand="DELETE FROM [Tbl_Div] WHERE divId=@divId"></asp:SqlDataSource>
		    </div>
			</div>
		</div>
		</div>
</asp:Content>
