<%@ Page Title="" Language="C#" MasterPageFile="~/AdminDashboard/main.Master" AutoEventWireup="true" CodeBehind="addSem.aspx.cs" Inherits="LMS.AdminDashboard.WebForm10" %>
	<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"> </asp:Content>
	<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
		<div class="card text-center">
			<div class="card-header text-light bg-danger fw-bold p-2">Add Semester</div>
			<div class="card-body">
				<div class="row">
					<div class="col gap-1">
						<asp:label CssClass="text-center" id="libmsg" runat="server" Text="result" Visible="false"></asp:label>
						<div class="form-floating mb-3">
							<asp:DropDownList CssClass="form-control" ID="ddDepart" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddDepart_SelectedIndexChanged">
								<asp:ListItem>Select Department</asp:ListItem>
							</asp:DropDownList>
							<label for="ddDepart">Department</label>
						</div>
						<div class="form-floating mb-3">
							<asp:DropDownList CssClass="form-control" ID="ddClass" runat="server" AutoPostBack="true">
								<asp:ListItem>Select Class</asp:ListItem>
							</asp:DropDownList>
							<label for="ddClass">Class</label>
						</div>
						<div class="form-floating mb-3">
							<asp:TextBox CssClass="form-control" ID="CSem" runat="server" placeholder="Sememter Name"></asp:TextBox>
							<asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="*" ControlToValidate="CSem"></asp:RequiredFieldValidator>
							<label for="CSem">Sememter Name</label>
						</div>
						<div class="row form-group ms-5 me-5 gap-1">
							<asp:Button CssClass="btn btn-success w-20 btn-block btn-lg" ID="SemSubmit" runat="server" Text="Save" OnClick="SemSubmit_Click" /> </div>
					</div>
				</div>
				<asp:GridView ID="Gridview" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="semId" DataSourceID="SqlDataSource1">
                    <Columns>
                        <asp:BoundField DataField="semId" HeaderText="semId" InsertVisible="False" ReadOnly="True" SortExpression="semId" />
                        <asp:BoundField DataField="semName" HeaderText="semName" SortExpression="semName" />
                        <asp:BoundField DataField="className" HeaderText="className" SortExpression="className" />
                        <asp:BoundField DataField="editDate" HeaderText="editDate" SortExpression="editDate" />
                    </Columns>
                    <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
                    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
                    <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
                    <RowStyle BackColor="White" ForeColor="#330099" />
                    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
                    <SortedAscendingCellStyle BackColor="#FEFCEB" />
                    <SortedAscendingHeaderStyle BackColor="#AF0101" />
                    <SortedDescendingCellStyle BackColor="#F6F0C0" />
                    <SortedDescendingHeaderStyle BackColor="#7E0000" />
                </asp:GridView>
				<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:LSMConnectionString1 %>" SelectCommand="SELECT * FROM [Tbl_Sem]" UpdateCommand="UPDATE [Tbl_Sem] SET [semName]=@semName, [className]=@className, [editDate]=@editDate WHERE [semID]=@semID" DeleteCommand="DELETE [Tbl_Sem] WHERE [semID]=@semID"></asp:SqlDataSource>
			</div>
		</div>
			</asp:Content>