<%@ Page Title="" Language="C#" MasterPageFile="~/AdminDashboard/main.Master" AutoEventWireup="true" CodeBehind="faculty.aspx.cs" Inherits="LMS.AdminDashboard.WebForm3" %>
	<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"> </asp:Content>
	<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <div class="row">
			<div class="col mb-2">
				<div class="card p-0">
					<div class="card-header text-light d-flex justify-content-between align-items-center bg-danger fw-bold">Faculty List
						<asp:Button ID="Button4" class="btn btn-outline-light" runat="server" Text="Add New" OnClick="Button1_Click"></asp:Button>
					</div>
					<div class="card-body p-0">
						<!-- <div class="row g-1" id="datatable"></div> -->
                        <asp:GridView ID="gridview" CssClass="table table-striped table-bordered table-sm" runat="server" AutoGenerateColumns="False" DataKeyNames="staffId" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                            <Columns>
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="staffId" HeaderText="staffId" InsertVisible="False" ReadOnly="True" SortExpression="staffId" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="firstName" HeaderText="firstName" SortExpression="firstName" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="middleName" HeaderText="middleName" SortExpression="middleName" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="lastName" HeaderText="lastName" SortExpression="lastName" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="mobile" HeaderText="mobile" SortExpression="mobile" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="email" HeaderText="email" SortExpression="email" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="username" HeaderText="username" SortExpression="username" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="password" HeaderText="password" SortExpression="password" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="departmentId" HeaderText="departmentId" SortExpression="departmentId" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="departmentName" HeaderText="departmentName" SortExpression="departmentName" />
                            </Columns>
                        </asp:GridView>
					    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:LSMConnectionString1 %>" SelectCommand="SELECT * FROM [Tbl_Staff]" UpdateCommand="UPDATE Tbl_Staff SET firstName=@firstName,middleName=@middleName,lastName=@lastName,mobile=@mobile,email=@email,username=@username,password=@password,departmentId=@departmentId,departmentName=@departmentName WHERE staffId=@staffId" DeleteCommand="DELETE FROM [Tbl_Staff] WHERE staffId=@staffId"></asp:SqlDataSource>
					</div>
				</div>
			</div>
		</div>
		<!-- <script>
            const container = document.getElementById('datatable');

            function createCrad(number) {
                const mainCol = document.createElement('div');
                mainCol.className = "col-lg-2";
                const card = document.createElement('div');
                card.className = "card";
                const cardH = document.createElement('div');
                cardH.className = "card-header";
                cardH.innerText = "Name: " + number;
                const cardImg = document.createElement('img');
                cardImg.className = "card-img-top img-thumbnail";
                cardImg.src = "../img/icon.png";
                const cardB = document.createElement('div');
                cardB.className = "card-body d-grid gap-1";
                const ButtonEdit = document.createElement('button');
                ButtonEdit.className = "btn btn-primary w-20 btn-block btn-s";
                ButtonEdit.innerText = "Edit";
                const ButtonView = document.createElement('button');
                ButtonView.className = "btn btn-success w-20 btn-block btn-s";
                ButtonView.innerText = "View";
                const ButtonRemove = document.createElement('button');
                ButtonRemove.className = "btn btn-danger w-20 btn-block btn-s";
                ButtonRemove.innerText = "Remove";
                cardB.appendChild(ButtonEdit);
                cardB.appendChild(ButtonView);
                cardB.appendChild(ButtonRemove);
                card.appendChild(cardH);
                card.appendChild(cardImg);
                card.appendChild(cardB)
                mainCol.append(card);
                return mainCol;
            }
            container.appendChild(createCrad(1));
            container.appendChild(createCrad(2));
            container.appendChild(createCrad(3));
            container.appendChild(createCrad(4));
            container.appendChild(createCrad(5));
            container.appendChild(createCrad(6));
            container.appendChild(createCrad(7));
		</script> -->
	</asp:Content>