<%@ Page Title="" Language="C#" MasterPageFile="~/AdminDashboard/main.Master" AutoEventWireup="true" CodeBehind="faculty.aspx.cs" Inherits="LMS.AdminDashboard.WebForm3" %>
	<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"> </asp:Content>
	<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <div class="row">
			<div class="col mb-2">
				<div class="card p-0">
					<div class="card-header text-light d-flex justify-content-between align-items-center bg-danger fw-bold">Faculty List
						<asp:Button ID="Button4" class="btn btn-outline-light" runat="server" Text="Add New" OnClick="Button1_Click"></asp:Button>
					</div>
					<div class="card-body p-0">
						
                            <asp:Label CssClass="text-center" ID="libmsg" runat="server" Text="result" Visible="false"></asp:Label>
                        <asp:GridView ID="gridview" CssClass="table table-striped table-bordered table-sm" runat="server" AutoGenerateColumns="False" DataKeyNames="staffId"  AllowPaging="True" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="Select from drop down" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
                        <Columns>
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="staffId" HeaderText="staffId" InsertVisible="False" ReadOnly="True" SortExpression="staffId" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="firstName" HeaderText="firstName" SortExpression="firstName" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="middleName" HeaderText="middleName" SortExpression="middleName" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="lastName" HeaderText="lastName" SortExpression="lastName" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="mobile" HeaderText="mobile" SortExpression="mobile" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="email" HeaderText="email" SortExpression="email" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="username" HeaderText="username" SortExpression="username" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="password" HeaderText="password" SortExpression="password" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="departId" HeaderText="departId" SortExpression="departId" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="departName" HeaderText="departName" SortExpression="departName" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="editDate" HeaderText="editDate" SortExpression="editDate" />
                            </Columns>
                        </asp:GridView>
					</div>
				</div>
			</div>
		</div>
	</asp:Content>