<%@ Page Title="" Language="C#" MasterPageFile="~/AdminDashboard/main.Master" AutoEventWireup="true" CodeBehind="feedback.aspx.cs" Inherits="LMS.AdminDashboard.WebForm11" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <div class="card p-0">
					<div class="card-header text-light d-flex justify-content-between align-items-center bg-danger fw-bold">
                        Feedbacks
					</div>
					<div class="card-body p-0">
						<!-- <div class="row g-1" id="datatable"></div> -->
                        <asp:GridView ID="gridview" CssClass="table table-striped table-bordered table-sm" runat="server" AutoGenerateColumns="False" DataKeyNames="feedBackId" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True">
                            <Columns>
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="feedBackId" HeaderText="feedBackId" InsertVisible="False" ReadOnly="True" SortExpression="feedBackId" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="email" HeaderText="email" SortExpression="email" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="mobile" HeaderText="mobile" SortExpression="mobile" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="feedBackMsg" HeaderText="feedBackMsg" SortExpression="feedBackMsg" />
                                <asp:BoundField ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center bg-danger text-capitalize text-light" DataField="createdDate" HeaderText="createdDate" SortExpression="createdDate" />
                            </Columns>
                        </asp:GridView>
					    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:LSMConnectionString1 %>" SelectCommand="SELECT * FROM [Tbl_Feedback]"></asp:SqlDataSource>
					</div>
				</div>
</asp:Content>
